### ISSUE TITLE
Add a new feature to allow the users to parameterize the SLC transporters

### ISSUE THREAD

**Issue by WeiweiAi** [Niloofar-Sh/static_website_Jlab#1]
We need to add a new feature to allow the users to parameterize the SLC transporters. 
The new feature should cover:
1. An interface for the users to upload the experimental data file (e.g.,  .csv file format), and describe the experiment data, e.g., column 1 is Ca+ in the cytosol, etc.
2. A function to process the inputs from the users, such as the selected template, experimental data, etc. to produce a DataFrame and model function expression, which are used for parameterization.
3. A function to take the DataFrame and the model function expression to set up the optimization algorithm and perform the parameterization, returning the parameter fitting result. As discussed, the result can be a dictionary.
4. A function to plot the fitting result and original experimental data, and save it to a png file? (This is beyond the discussion, please comment on it @Niloofar-Sh )
5. An interface to display the plot (please comment on it @Niloofar-Sh ).

**Comment by Niloofar-Sh** [comment]
Uploading experimental data as a csv file is now available.
It generates a DataFrame from the imported csv file and parameterizes the steady-state equation.
